name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test workflow trigger
        run: |
          echo "Workflow triggered successfully!"
          echo "Branch: ${{ github.head_ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Commit: ${{ github.sha }}"
