name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (root)
        run: npm ci

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Setup iOS Simulator
        run: |
          xcrun simctl list runtimes
          xcrun simctl create "iPhone 15" "iPhone 15" "com.apple.CoreSimulator.SimRuntime.iOS-18-6"
          xcrun simctl boot "iPhone 15"

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Build and Install App
        working-directory: apps/main
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          npx expo run:ios -d "iPhone 15"

      - name: Run E2E tests
        working-directory: apps/main
        env:
          EXPO_PUBLIC_OPENAI_API_KEY: ${{ secrets.EXPO_PUBLIC_OPENAI_API_KEY }}
        run: |
          npm run e2e
